apiVersion: apps/v1
kind: Deployment
metadata:
 name: krutrim_landing-deployment
spec:
 replicas: 3
 selector:
    matchLabels:
      app: nextjs
 template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: ankitmohapatra/krutrim_landing:v4
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
 name: krutrim_landing-service
spec:
 selector:
    app: nextjs
 ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
 type: LoadBalancer